version: "3.3"
volumes:
  pgdata:
services:
  test-loan-db:
    restart: always
    image: postgres:11.5
    environment:
      POSTGRES_PASSWORD: "devpassword"
      POSTGRES_USER: "taein"
      POSTGRES_DB: "taein"
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - ./configs/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    expose:
      - "5432"
    ports:
      - "127.0.0.1:5432:5432"
  taein-crawler:
    build:
      context: .
      dockerfile: Dockerfile-taein-crawler
      args:
        env: local
    command: >
      python manage.py run
    volumes:
      - ./app/taein-crawler/:/crawler/app/taein-crawler/
      - ./lib/crawler-python-commons:/crawler/lib/crawler-python-commons
    environment:
      CRAWLER_ENVIRONMENT: local
  taein-store:
    build:
      context: .
      dockerfile: Dockerfile-taein-store
      args:
        env: local
    command: >
      python manage.py run
    volumes:
      - ./app/taein-store/:/store/app/taein-store/
      - ./lib/crawler-python-commons:/store/lib/crawler-python-commons
    environment:
      STORE_ENVIRONMENT: local
      STORE_SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://taein:devpassword@test-loan-db:5432/taein
    depends_on:
      - test-loan-db